### ISSUE TITLE
Replace graphql dependency with gql_link

### ISSUE THREAD

**Issue by ninogjoni** [felangel/fresh#59]
It is just an idea, but can the dependency be changed from graphql to gql_link? Is it even possible?
The maintainer of ferry mentioned it in a comment: https://github.com/gql-dart/ferry/issues/296

Any thoughts about the comment?

**Comment by knaeckeKami** [comment]
Maintainer of ferry and gql-dart here.

What the user is asking here is just to swap out the dependency from `graphql` to `gql_link`.
If you follow the import, you can see that the `Link` class exported from package `graphql` is from gql_link, so you are using gql_link anyway.

All graphql clients in Dart that I know of (graphql, ferry, and artemis) use some base packages from the gql-dart ecosystem. So if you just depended on gql_link instead of grapqhl, all graphql clients could use this package without pulling in a whole other graphql client as a dependency.

**Comment by chungonion** [comment]
> Hi!
> 
> Maintainer of ferry and gql-dart here.
> 
> What @ngjoni is asking here is just to swap out the dependency from `graphql` to `gql_link`. (https://pub.dev/packages/gql_link ) If you follow the import, you can see that the `Link` class exported from package `graphql` is from gql_link, so you are using gql_link anyway.
> 
> All graphql clients in Dart that I know of (graphql, ferry, and artemis) use some base packages from the gql-dart ecosystem. So if you just depended on gql_link instead of grapqhl, all graphql clients could use this package without pulling in a whole other graphql client as a dependency.

Hi @felangel , thanks for your great work on this library! Just wonder would that be possible as it seems there are some conflicts on resolving with latest ferry and latest graphql_flutter package together... 🧐 

Thanks!

**Comment by ebsangam** [comment]
This can be closed:
https://github.com/felangel/fresh/pull/77
